language: java
before_install:
- cp .travis.maven.settings.xml $HOME/.m2/settings.xml
env: # important!
branches:
  only:
  - master
  - /^\d+\.\d+$/
jobs:
  include:
    - jdk: oraclejdk8
      script: mvn -q clean verify -B
    - if: type != pull_request
      jdk: openjdk11
      script: mvn -q clean verify -B
    - if: type != pull_request
      jdk: oraclejdk8
      script: mvn -q clean verify -B -PtestNativeTransport
    - if: type != pull_request
      jdk: oraclejdk8
      script: mvn -q clean verify -B -PtestDomainSockets
    - stage: deploy
      script: bash .travis.deploy.artifacts.sh
notifications:
  email:
    recipients:
      - vertx3-ci@googlegroups.com
    on_success: always
    on_failure: always
